words = [
    "ADPCM",
    "ALAC",
    "CLI",
    "IPC",
    "LLM",
    "LRC",
    "MPD",
    "MPRIS",
    "TBD",
    "VLC",
    "WIP",
    "alsa",
    "calloop",
    "chilen",
    "daemon",
    "frontends",
    "interprocess",
    "mpris",
    "multivariant",
    "rmp",
    "rodio",
    "sctk",
    "serde",
    "silverblue",
    "smol",
    "tpaau",
    "trx",
    "vlc",
    "vorbis",
    "wgpu",
    "winit",
    "zbus",
]
