[package]
name = "chilen"
version = "0.1.0"
authors = [ "tpaau <tpaau-17db@tutamail.com>" ]
edition = "2024"
license = "GPL-3.0-or-later"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[dependencies]
env_logger = "0.11.10"
log = "0.4.29"
clap = { version = "4.5.53", features = [ "derive", "cargo" ] }
serde = { version = "1.0.228", features = [ "derive" ] }
dirs = "6.0.0"
iced = { version = "0.14.0", features = [ "advanced", "image" ] }
iced_widget = { version = "0.14.2" }
chilen_backend = { path = "chilen_backend" }
iced_m3 = { path = "iced_m3" }
rfd = "0.17.2"
iced_core = "0.14.0"

[features]
mpris = [ "chilen_backend/mpris" ]
linux_package = [ "mpris" ]
linux_flatpak = [ "mpris" ]
windows = []
macos = []
default = []

[workspace]
members = [ "chilen_backend", "iced_m3" ]
