[package]
name = "m3u8"
version = "0.1.0"
edition = "2024"
authors = [ "tpaau <tpaau-17db@tutamail.com>" ]
license = "MIT"

[dependencies]
log = "0.4.32"
nom = { version = "8.0.0", optional = true }
nom-language = { version = "0.1.0", optional = true }

[features]
parser = [ "dep:nom", "dep:nom-language" ]
default = [ "parser" ]
