name: CI

on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
  DEPS_APT: libasound2-dev

jobs:
  build:
    name: Check format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: rustup component add --toolchain nightly rustfmt
    - run: cargo fmt --all --check

  cargo-deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: EmbarkStudios/cargo-deny-action@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v6

      - run: sudo apt-get update -y
      - run: sudo apt install -y ${{ env.DEPS_APT }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - run: cargo build --verbose

      - name: Run tests with no default features
        run: cargo test --workspace --no-default-features --verbose

      - name: Run tests with default configuration
        run: cargo test --workspace --verbose

  # docs:
  #   name: Docs
  #   needs: test
  #   permissions:
  #     pages: write
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6

  #     - run: sudo apt-get update -y
  #     - run: sudo apt install -y ${{ env.DEPS_APT }}

  #     - name: Generate rustdoc documentation
  #       run: cargo doc --no-deps -p chilen_ipc -p chilen_daemon

  #     - run: mkdir -p publish/
  #     - run: cp -r ./target/doc/* ./publish/

  #     - name: Deploy
  #       if: github.ref == 'refs/heads/main'
  #       uses: peaceiris/actions-gh-pages@v4
  #       with:
  #         personal_token: ${{ secrets.PERSONAL_TOKEN }}
  #         publish_dir: ./publish
  #         force_orphan: true        
