name: Check format

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup component add --toolchain nightly rustfmt
    - run: cargo fmt --all --check
